name: teste_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.0.0+3
  sqflite_common_ffi_web: 0.4.5+4  # Adicione esta linha para suporte à web
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  http: ^1.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
